variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'
  JULIA_CUDA_VERBOSE: 'true'
  JULIA_CUDA_USE_BINARYBUILDER: 'false' # reduce CI network traffic

# See: https://github.com/JuliaGPU/gitlab-ci
include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

# the "primary" target, where we require a new GPU to make sure all tests are run
julia:1.5:
  extends:
    - .julia:1.5
    - .test
  tags:
    - nvidia
  variables:
    CI_THOROUGH: 'true'

test:nightly:
  extends:
    - .julia:nightly
    - .test
  allow_failure: true

# other tasks
coverage:
  extends:
    - .julia:1.5
    - .coverage
    