language: julia

os:
  - osx
  - linux

julia:
  # - nightly
  # - 0.6.0
  - 0.6.2

before_script:
 - julia -e 'Pkg.add("JLD2"); Pkg.add("SpecialFunctions"); Pkg.add("CuArrays");'
 - julia -e 'Pkg.add("Interpolations"); Pkg.add("Requires");'
 # - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall"); using PyPlot;'

# this was the old way of running tests before runtests.jl
# script:
#   - julia test/test_grid.jl
#   - julia test/test_twodturb.jl
#   - julia test/test_utils.jl

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("FourierFlows",coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("FourierFlows")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("FourierFlows")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("FourierFlows")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

notifications:
  email: true
